package gestionStructure;

import gestionLieux.*;
import nezdames.serialisation.NezDamesSerialisation;
import classesMetier.Lieu;
import classesMetier.PersonneStructure;
import classesMetier.Structure;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static nezdames.serialisation.NezDamesSerialisation.lesPersonnesStructures;

/**
 *
 * @author boulom
 */
public class StructureAjouter extends javax.swing.JFrame {

    public StructureAjouter() {
        initComponents();
        
        
        //on remplit la combobox
        jContact.removeAllItems();
        jResponsable.removeAllItems();
        //on remplit la JComboBox
        for (PersonneStructure unContact : NezDamesSerialisation.lesPersonnesStructures) {
            jContact.addItem(unContact.getNomPersonne());
        }
         for (PersonneStructure unResponsable : NezDamesSerialisation.lesPersonnesStructures) {
            jResponsable.addItem(unResponsable.getNomPersonne());
        } 
            
        //pour que toute l'application ne se ferme pas quand on clique sur la croix rouge
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lblTitre4 = new javax.swing.JLabel();
        txtnumSiret = new javax.swing.JTextField();
        btnEnvoyer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        lblCode = new javax.swing.JLabel();
        lblRue = new javax.swing.JLabel();
        txtcodePostal = new javax.swing.JTextField();
        lblSiret = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtcodeNafOUApe = new javax.swing.JTextField();
        txtadresseVille = new javax.swing.JTextField();
        lblTitre1 = new javax.swing.JLabel();
        lblImageOlivier = new javax.swing.JLabel();
        lblImageManu = new javax.swing.JLabel();
        txtraisonSoc = new javax.swing.JTextField();
        txtadresseRue = new javax.swing.JTextField();
        lblVille = new javax.swing.JLabel();
        lblCodePostal = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        lblResponsable = new javax.swing.JLabel();
        jContact = new javax.swing.JComboBox();
        jResponsable = new javax.swing.JComboBox();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));

        lblTitre4.setFont(new java.awt.Font("Hannotate SC", 1, 18)); // NOI18N
        lblTitre4.setForeground(new java.awt.Color(255, 153, 51));

        txtnumSiret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumSiretActionPerformed(evt);
            }
        });

        btnEnvoyer.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        btnAnnuler.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        lblCode.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblCode.setForeground(new java.awt.Color(255, 153, 51));
        lblCode.setText("codeNafOuApe");

        lblRue.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblRue.setForeground(new java.awt.Color(255, 153, 51));
        lblRue.setText("adresseRue");

        txtcodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodePostalActionPerformed(evt);
            }
        });

        lblSiret.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblSiret.setForeground(new java.awt.Color(255, 153, 51));
        lblSiret.setText("numeroSiret");

        lblNom.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblNom.setForeground(new java.awt.Color(255, 153, 51));
        lblNom.setText("raisonSociale");

        txtcodeNafOUApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeNafOUApeActionPerformed(evt);
            }
        });

        lblTitre1.setFont(new java.awt.Font("Hannotate SC", 1, 18)); // NOI18N
        lblTitre1.setForeground(new java.awt.Color(255, 153, 51));
        lblTitre1.setText("CRÉATION D'UNE STRUCTURE ");

        lblImageOlivier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitOlivier.png"))); // NOI18N

        lblImageManu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitManu.png"))); // NOI18N

        txtraisonSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtraisonSocActionPerformed(evt);
            }
        });

        lblVille.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblVille.setForeground(new java.awt.Color(255, 153, 51));
        lblVille.setText("adresseVille");

        lblCodePostal.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblCodePostal.setForeground(new java.awt.Color(255, 153, 51));
        lblCodePostal.setText("codePostal");

        lblMail.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblMail.setForeground(new java.awt.Color(255, 153, 51));
        lblMail.setText("mail");

        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        lblTelephone.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblTelephone.setForeground(new java.awt.Color(255, 153, 51));
        lblTelephone.setText("telephone");

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        lblContact.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 153, 51));
        lblContact.setText("contact");

        lblResponsable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(255, 153, 51));
        lblResponsable.setText("responsable");

        jContact.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContactActionPerformed(evt);
            }
        });

        jResponsable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnvoyer)
                        .addGap(34, 34, 34)
                        .addComponent(btnAnnuler))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImageManu)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitre4)
                                .addGap(128, 128, 128))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTitre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblImageOlivier))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCode)
                            .addComponent(lblSiret)
                            .addComponent(lblNom)
                            .addComponent(lblRue)
                            .addComponent(lblVille)
                            .addComponent(lblCodePostal)
                            .addComponent(lblMail)
                            .addComponent(lblTelephone)
                            .addComponent(lblContact)
                            .addComponent(lblResponsable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodeNafOUApe)
                            .addComponent(txtnumSiret)
                            .addComponent(txtraisonSoc)
                            .addComponent(txtadresseRue)
                            .addComponent(txtadresseVille)
                            .addComponent(txtcodePostal)
                            .addComponent(txtMail)
                            .addComponent(txtTel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(207, 207, 207))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblImageOlivier)
                                .addComponent(lblImageManu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblTitre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitre4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodeNafOUApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSiret)
                            .addComponent(txtnumSiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNom)
                            .addComponent(txtraisonSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRue)
                            .addComponent(txtadresseRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVille)
                            .addComponent(txtadresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodePostal)
                            .addComponent(txtcodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMail)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelephone)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblContact))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResponsable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnvoyer)
                    .addComponent(btnAnnuler))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(629, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void txtraisonSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtraisonSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtraisonSocActionPerformed

    private void txtcodeNafOUApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeNafOUApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeNafOUApeActionPerformed

    private void txtcodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodePostalActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // fermeture de la fenêtre
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
        // test qui vérifie que les champs sont remplis

        if (txtcodeNafOUApe.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Il faut saisir le code Naf ou Ape");
        } else {

            if (txtnumSiret.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(null, "Il faut saisir le code postal");
            } else {
                if (txtraisonSoc.getText().compareTo("") == 0) {
                    JOptionPane.showMessageDialog(null, "Il faut saisir le code naf ou Ape");
                } else {
                    if (txtadresseRue.getText().compareTo("") == 0) {
                        JOptionPane.showMessageDialog(null, "Il faut saisir le numéro de siret");
                    } else {
                        if (txtadresseVille.getText().compareTo("") == 0) {
                            JOptionPane.showMessageDialog(null, "Il faut saisir le mail ");
                        } else {
                            if (txtcodePostal.getText().compareTo("") == 0) {
                                JOptionPane.showMessageDialog(null, "Il faut saisir le numéro de téléphone ");
                            } else {
                                if (txtMail.getText().compareTo("") == 0) {
                                    JOptionPane.showMessageDialog(null, "Il faut saisir la raison social ");
                                } else {
                                    if (txtTel.getText().compareTo("") == 0) {
                                        JOptionPane.showMessageDialog(null, "Il faut saisir l'adresse de la rue ");
                                    } else {

                                        //recherche du dernier id de structure donné
                                        int idMax = 0;
                                        for (Structure laStructure : NezDamesSerialisation.lesStructures) {
                                            if (laStructure.getIdStructure() > idMax) {
                                                idMax = laStructure.getIdStructure();
                                            }
                                        }
                                        PersonneStructure p=null;
                                        for(PersonneStructure unePersonne:lesPersonnesStructures){
                                            if (unePersonne.getNomPersonne().compareTo(jContact.getSelectedItem().toString())==0){
                                                p=unePersonne;
                                            }
                                        }
                                        
                                          PersonneStructure a=null;
                                        for(PersonneStructure unePersonne:lesPersonnesStructures){
                                            if (unePersonne.getNomPersonne().compareTo(jResponsable.getSelectedItem().toString())==0){
                                                a=unePersonne;
                                            }
                                        }
                                        
                                        // ajout d'un lieu à la collection lesStructures
                                        NezDamesSerialisation.lesStructures.add(new Structure(idMax + 1,
                                                txtcodeNafOUApe.getText(), Integer.parseInt(txtnumSiret.getText()), 
                                                txtraisonSoc.getText(), txtadresseRue.getText(), txtadresseVille.getText(),
                                                Integer.parseInt(txtcodePostal.getText()), txtMail.getText(),
                                                Integer.parseInt(txtTel.getText()), p, a));
                                        JOptionPane.showMessageDialog(null, "Structure ajouté.");

                                        this.dispose();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void txtnumSiretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumSiretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumSiretActionPerformed

    private void jContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StructureAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StructureAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StructureAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StructureAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StructureAjouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JComboBox jContact;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jResponsable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCodePostal;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblImageManu;
    private javax.swing.JLabel lblImageOlivier;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblRue;
    private javax.swing.JLabel lblSiret;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitre1;
    private javax.swing.JLabel lblTitre4;
    private javax.swing.JLabel lblVille;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtadresseRue;
    private javax.swing.JTextField txtadresseVille;
    private javax.swing.JTextField txtcodeNafOUApe;
    private javax.swing.JTextField txtcodePostal;
    private javax.swing.JTextField txtnumSiret;
    private javax.swing.JTextField txtraisonSoc;
    // End of variables declaration//GEN-END:variables
}
